name: macos-latest

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: make bsd
    - run: brew install ccache

    - env:
        MKN_LIB_LINK_LIB: 1
        KUL_GIT_CO: --depth 1
      run: |
        mkdir ~/.maiken
        cp res/mkn/clang.yml ~/.maiken/settings.yaml
        KLOG=3 ./mkn build -dtKOW 9 -g 0
        KLOG=3 ./mkn build -dtOp test_mod
        KLOG=3 ./mkn build test pack -Op test

    - uses: actions/upload-artifact@v1
      env:
        KUL_GIT_CO: --depth 10
      with:
        name: mkn
        path: bin/build/mkn
