name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        cc: [gcc, clang]
    steps:
    - uses: actions/checkout@v6
    - run: ./res/ci/nixish_setup.sh && make nix
    - run: ldd mkn
    - run: |
        mkdir -p ~/.maiken/app/mkn
        cp -r $PWD ~/.maiken/app/mkn/master
    - env:
        KLOG: 3
      run: python3 res/ci/build.py ubuntu_${{ matrix.cc }}
    - run: ldd bin/build/mkn
    - run: ldd bin/bin_shared/mkn

  manylinux:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64:latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - run: ./res/ci/nixish_setup.sh && make nix
    - run: ldd mkn
    - env:
        KLOG: 3
      run: python3 res/ci/build.py manylinux_gcc
    - run: ldd bin/build/mkn

  macos:
    strategy:
      matrix:
        os: [macos-14, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - run: ./res/ci/nixish_setup.sh && make bsd
    - run: |
        mkdir -p ~/.maiken/app/mkn
        cp -r $PWD ~/.maiken/app/mkn/master
    - env:
        KLOG: 3
      run: python3 res/ci/build.py macos_clang

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - run: bash -c "rm /bin/link" # interferes with cl/link.exe
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
    - shell: bash
      run: |
        mkdir -p ~/maiken/app/mkn
        cp -r $PWD ~/maiken/app/mkn/master
        ./res/ci/win_build.sh
    - shell: cmd
      env:
        KLOG: 3
      run: python res/ci/build.py win_cl

  ubuntu_python:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        python-version: ['3.13', '3.14']
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: |
        ./res/ci/nixish_setup.sh && make nix
        sudo cp mkn /usr/bin
        python3 -m pip install -r test/github/requirements.txt
        mkn clean build -p github -dtOa "-fPIC -std=c++20"
        ./test/github/test_github_api.sh

