name: ubuntu-python-latest

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: |
        ./res/ci/nixish_setup.sh && make nix
        sudo cp mkn /usr/bin
        python3 -m pip install -r test/github/requirements.txt
        mkn clean build -p github -dtOa "-fPIC -std=c++17"
        ./test/github/test_github_api.sh
