name: macos-latest

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - run: ./res/ci/nixish_setup.sh && make bsd

    - env:
        MKN_LIB_LINK_LIB: 1
        KUL_GIT_CO: --depth 1
      run: |
        brew install ccache
        mkdir ~/.maiken && cp res/mkn/clang.yml ~/.maiken/settings.yaml
        KLOG=3 ./mkn build -dtKO 2 -W 9 -g 0
        KLOG=3 ./mkn build -dtOp test_mod
        KLOG=3 ./mkn build test pack -Op test
