name: Production Builds
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
      # Build on Linux, Windows and MacOS
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2

        - if: matrix.os == 'windows-latest'
          run: bash -c "rm /bin/link" # interferes with cl/link.exe
        - if: matrix.os == 'windows-latest'
          uses: ilammy/msvc-dev-cmd@v1
          with:
            arch: amd64
        - if: matrix.os == 'windows-latest'
          shell: cmd
          env:
            MKN_CL_PREFERRED: 1
            KUL_GIT_CO: --depth 1
          run: |
            bash -c ./res/ci/win_build.sh
            mkn build -dtKOg 0 -a "-std:c++17 -EHsc"


        - if: matrix.os == 'ubuntu-latest'
          env:
            MKN_GCC_PREFERRED: 1
            KUL_GIT_CO: --depth 1
          run: |
            make nix
            KLOG=3 ./mkn build -dtKa "-std=c++17 -fPIC" -O 2 -g 0 -W 9 -o mkn_nix


        - if: matrix.os == 'macos-latest'
          env:
            KUL_GIT_CO: --depth 1
          run: |
            make bsd
            KLOG=3 ./mkn build -dtKOW 9 -g 0 -a "-std=c++17 -fPIC" -o mkn_osx


        - if: matrix.os == 'ubuntu-latest'
          uses: actions/upload-artifact@v2
          with:
            name: maiken-${{ matrix.os }}
            path: bin/build/mkn_nix
            retention-days: 1

        - if: matrix.os == 'windows-latest'
          uses: actions/upload-artifact@v2
          with:
            name: maiken-${{ matrix.os }}
            path: bin/build/mkn.exe
            retention-days: 1

        - if: matrix.os == 'macos-latest'
          uses: actions/upload-artifact@v2
          with:
            name: maiken-${{ matrix.os }}
            path: bin/build/mkn_osx
            retention-days: 1

  release:
    name: "Prelease"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - name: Display fetched artifacts
        run: ls -R
      - name: Emit a Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            maiken-windows-latest/mkn.exe
            maiken-macos-latest/mkn_osx
            maiken-ubuntu-latest/mkn_nix

